version: '3.9'
services:
  running_on_dart:
    build: .
    container_name: running_on_dart
    env_file:
     - .env
    links:
      - db
      - lavalink
    depends_on:
      - db
      - lavalink

  db:
    image: postgres:13.5
    container_name: running_on_dart_db
    restart: always
    ports:
      - 5432:5432
    env_file:
     - .env
    volumes:
      - "rod_db:/var/lib/postgresql/data"

  lavalink:
    image: fredboat/lavalink:master
    container_name: running_on_dart_lavalink
    restart: always
    expose:
      - 2333
    volumes:
     - ./lavalink.yml:/opt/Lavalink/application.yml

volumes:
  rod_db:
    driver: local
